DROP TABLE IF EXISTS utxo CASCADE;
DROP TABLE IF EXISTS payout_transaction CASCADE;
DROP TABLE IF EXISTS share CASCADE;
DROP TABLE IF EXISTS block CASCADE;
DROP TABLE IF EXISTS payout_address CASCADE;
DROP TABLE IF EXISTS minute_share CASCADE;
DROP TABLE IF EXISTS credit CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS payout CASCADE;
DROP TYPE IF EXISTS block_status CASCADE;
DROP TYPE IF EXISTS aggregation_type CASCADE;
DROP SEQUENCE IF EXISTS internal_users_id_seq;
DROP SEQUENCE IF EXISTS users_id_seq;

